transform: 
  source: # GaussDB
    host:  
    user:  
    password:  
    port:  
    dbname:  
    schema:  
  target: # DWS
    host:  
    user:  
    password:  
    port:  
    dbname:  
    schema:  